//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;
using System.Web.Mvc;
namespace BugTracker.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel;

    public partial class Ticket
    {
        public Ticket()
        {
            this.TicketAttachments = new HashSet<TicketAttachment>();
            this.TicketComments = new HashSet<TicketComment>();
            this.TicketHistories = new HashSet<TicketHistory>();
            this.TicketNotifications = new HashSet<TicketNotification>();
            this.HideTicket = false;
            //this.OwnerUser = new ApplicationUser();
            //this.AssignedToUser = new ApplicationUser();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        [AllowHtml]
        public string Description { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public Nullable<System.DateTimeOffset> Updated { get; set; }
        public int ProjectId { get; set; }
        public int TicketTypeId { get; set; }
        public int TicketPriorityId { get; set; }
        public int TicketStatusId { get; set; }
        public string OwnerUserId { get; set; }
        public string AssignedToUserId { get; set; }
        public bool HideTicket { get; set; }
        public bool TicketRead { get; set; }

        [DisplayName("Owner")]
        public virtual ApplicationUser OwnerUser { get; set; }
        [DisplayName("AssignedTo")]
        public virtual ApplicationUser AssignedToUser { get; set; }
        [DisplayName("Status")]
        public virtual TicketStatus TicketStatus { get; set; }
        [DisplayName("Priority")]
        public virtual TicketPriority TicketPriority { get; set; }
        [DisplayName("Type")]
        public virtual TicketType TicketType { get; set; }
        [DisplayName("Project")]
        public virtual Project Project { get; set; }

        public virtual ICollection<TicketAttachment> TicketAttachments { get; set; }
        public virtual ICollection<TicketComment> TicketComments { get; set; }
        public virtual ICollection<TicketHistory> TicketHistories { get; set; }
        public virtual ICollection<TicketNotification> TicketNotifications { get; set; }
    }
}
